### ISSUE TITLE
Locks in AWS config too early

### ISSUE THREAD

**Issue by limulus** [colbywhite/aws-cf-monitor#1]
Thanks so much for this module! It’s always awesome to find on npm the exact solution you want. :smile:

Here’s something that tripped me up using it, though it may be a result of my relative newness to `aws-sdk`. If you update the global `AWS.config` object after you’ve imported `aws-cf-monitor`, those updates are not manifested in calls to the `aws-cf-monitor` functions. For example:

```javascript
const AWS = require('aws-sdk')
AWS.config.update({ region: 'us-east-1' })

const CFMonitor = require('aws-cf-monitor')

AWS.config.update({ region: 'us-west-2' })
CFMonitor.updateStack({…}) // Operates on `us-east-1`, not `us-west-2`.
```

The work-around is to wait to `require('aws-cf-monitor')` until global configuration is complete. But maybe the right thing is for the `new AWS.CloudFormation()` call to happen inside the `*Stack()` functions, instead of during module loading?

**Comment by colbywhite** [comment]
That seems like a reasonable solution. Internally, that means the `*Stack()` methods would be doing a `BbPromise.promisifyAll(new AWS.CloudFormation())`, meaning that line of code would be in multiple methods. But that doesn't seem horrible, at least not for now considering the size of the project.

**Comment by limulus** [comment]
Thanks for making this fix!

FWIW, [lenticular](https://github.com/limulus/lenticular) is the project I am working on that is making use of this module.
