### ISSUE TITLE
Add createOrUpdate() support

### ISSUE THREAD

**Issue by mymattcarroll** [colbywhite/aws-cf-monitor#3]
Hi,

Firstly, this module is awesome!

We would like to use this module in CI context and would love to have a command we can call for new and existing stacks.

I would be happy to contribute if you'd like?

Thoughts?

**Comment by colbywhite** [comment]
@mymattcarroll, makes sense. `createOrUpdate` would create if it didn't exist, and update if it did. Seems straightforward enough. I'll play with it this weekend. If you go for it and beat me to it, I'll merge that.
